import "./globals.css";

import { USER_INFORMATION } from "@/app/constants";

export const metadata = {
    title: USER_INFORMATION.nickname,
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className="antialiased">
                { children }
            </body>
        </html>
    );
}
